function setup_S2_5_path()
% SETUP_S2_5_PATH Configure the cumulative validated-S2.4 + S2.5 overlay.
root=fileparts(mfilename('fullpath'));
paths={ ...
    fullfile(root,'frozen_parent','S2_3_online_mapping_v1_0_0_validated'), ...
    fullfile(root,'s2_4_shadow'), ...
    fullfile(root,'coupled','execution'),fullfile(root,'coupled','scenarios'), ...
    fullfile(root,'coupled','mission'),fullfile(root,'coupled','validation'), ...
    fullfile(root,'s2_5','sensors'),fullfile(root,'s2_5','perception'), ...
    fullfile(root,'s2_5','scenarios'),fullfile(root,'s2_5','mission'), ...
    fullfile(root,'s2_5','validation')};
for i=1:numel(paths)
    assert(exist(paths{i},'dir')==7,'S2_5:MissingPath','Missing path: %s',paths{i});
    addpath(paths{i},'-begin');
end
fprintf('S2.5 MATLAB PATH SETUP: PASS\n');
fprintf(' run_S2_5_coupled              : %s\n',which('run_S2_5_coupled'));
fprintf(' mission_lifecycle_manager_S2_5: %s\n',which('mission_lifecycle_manager_S2_5'));
fprintf(' mission_lifecycle_manager_S2_4: %s\n',which('mission_lifecycle_manager_S2_4'));
end
