% patch_initAllLanes_S2.m
% Minimal patcher for Stage S2.1 MATLAB runtime error:
% "Subscripted assignment between dissimilar structures" in initAllLanes_S2.
%
% Run this from MATLAB after adding only the S2.1 folder to the path.
% It patches the ACTIVE file returned by which('run_S2_lidar_slam'), creates a .bak copy,
% and verifies that the old failing whole-struct assignment is gone.

clc;
f = which('run_S2_lidar_slam');
if isempty(f)
    error('S2_1:Patch:NotOnPath','run_S2_lidar_slam.m is not on the MATLAB path.');
end
fprintf('Active run_S2_lidar_slam file:\n%s\n\n', f);

src = fileread(f);

oldExpr = ['function lanes=initAllLanes_S2\(cfg,meas\)[\s\S]*?' ...
           '%% =========================================================================\s*\n% ESKF PREDICTION'];

newBlock = [ ...
"function lanes=initAllLanes_S2(cfg,meas)" newline ...
"    names={'Primary IMU + all aids','Backup IMU + all aids','Primary IMU + VIO','Backup IMU + LiDAR'};" newline ...
"    imuIds=[0 1 0 1];useVio=[true true true false];useLidar=[true true false true];" newline ...
"    s=[repmat(0.05,1,3),repmat(0.12,1,3),deg2rad([3 3 4]),repmat(0.06,1,3),deg2rad([0.4 0.4 0.4]),0.20];P0=diag(s.^2);q0=qnormalize(meas.vioQ(1,:));" newline ...
"" newline ...
"    % Build a scalar prototype with the full field set, then replicate it." newline ...
"    % This avoids MATLAB's dissimilar-structure assignment when lanes starts" newline ...
"    % as struct([]) with no fields." newline ...
"    prototype=struct('id',0,'name','','imuId',0,'useVio',false,'useLidar',false, ..." newline ...
"        'useRange',true,'useBaro',true,'p',zeros(3,1),'v',zeros(3,1),'q',[1 0 0 0], ..." newline ...
"        'ba',zeros(3,1),'bg',zeros(3,1),'bbaro',0.12,'P',P0,'nisNormalized',zeros(0,1), ..." newline ...
"        'nisType',{cell(0,1)},'acceptedCount',0,'rejectedCount',0,'lastHorizontalAidTime',0, ..." newline ...
"        'lastVerticalAidTime',0,'lastAttitudeAidTime',0,'score',inf,'eligible',false,'reason','initialising');" newline ...
"    lanes=repmat(prototype,1,4);" newline ...
"" newline ...
"    for i=1:4" newline ...
"        lanes(i).id=i;" newline ...
"        lanes(i).name=names{i};" newline ...
"        lanes(i).imuId=imuIds(i);" newline ...
"        lanes(i).useVio=useVio(i);" newline ...
"        lanes(i).useLidar=useLidar(i);" newline ...
"        lanes(i).p=meas.vioP(1,:)';" newline ...
"        lanes(i).v=meas.vioV(1,:)';" newline ...
"        lanes(i).q=q0;" newline ...
"        lanes(i).ba=zeros(3,1);" newline ...
"        lanes(i).bg=zeros(3,1);" newline ...
"        lanes(i).bbaro=0.12;" newline ...
"        lanes(i).P=P0;" newline ...
"        lanes(i).nisNormalized=zeros(0,1);" newline ...
"        lanes(i).nisType=cell(0,1);" newline ...
"        lanes(i).acceptedCount=0;" newline ...
"        lanes(i).rejectedCount=0;" newline ...
"        lanes(i).lastHorizontalAidTime=0;" newline ...
"        lanes(i).lastVerticalAidTime=0;" newline ...
"        lanes(i).lastAttitudeAidTime=0;" newline ...
"        lanes(i).score=inf;" newline ...
"        lanes(i).eligible=false;" newline ...
"        lanes(i).reason='initialising';" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"%% =========================================================================" newline ...
"% ESKF PREDICTION" ];

[newSrc, n] = regexprep(src, oldExpr, newBlock, 'once');
if n ~= 1
    error('S2_1:Patch:PatternNotFound','Could not uniquely find initAllLanes_S2 block to patch. No file written.');
end

backup = [f '.bak_' datestr(now,'yyyymmdd_HHMMSS')];
copyfile(f, backup);
fid = fopen(f,'w');
if fid < 0
    error('S2_1:Patch:WriteFailed','Could not open active file for writing: %s', f);
end
cleanup = onCleanup(@()fclose(fid));
fwrite(fid, newSrc);
clear cleanup;

clear run_S2_lidar_slam;
clear functions;
rehash path;

patched = fileread(f);
if contains(patched, 'lanes(i)=struct')
    error('S2_1:Patch:VerifyFailed','Old failing lanes(i)=struct assignment is still present.');
end
if ~contains(patched, 'lanes=repmat(prototype,1,4)')
    error('S2_1:Patch:VerifyFailed','Prototype lane preallocation was not found after patch.');
end

fprintf('Patch applied successfully. Backup created:\n%s\n\n', backup);
fprintf('Now run:\n');
fprintf('clear functions; clear classes; close all; clc; rehash path;\n');
fprintf('which run_S2_lidar_slam -all\n');
fprintf('dbtype run_S2_lidar_slam 506:540\n');
fprintf('results = run_S2_lidar_slam(0,true,false,false);\n');
