function plot_S2_dashboard(gt,imu,vio,alt,lidar,est,lidarTruth, ...
    localLidar,globalLidar,loops,keyframes,summary,cfg,label,results_dir)
% PLOT_S2_DASHBOARD
% Creates a single tabbed Stage-S2 dashboard and saves every report tab.
%
% Place this file in the same folder as run_S2_lidar_slam.m, or add
% its folder to the MATLAB path. All plots appear as tabs in one window.
% Each tab is exported as a PNG; the complete tabbed dashboard is saved as
% one editable MATLAB FIG file in simulation/results/S2_visual_slam/.
%
% Saved report tabs
%   01_trajectory_6dof       3-D and projected flight trajectories
%   02_position_errors       ESKF/VIO/LiDAR error overlays and axis errors
%   03_attitude_tracking     Roll, pitch, yaw and total attitude error
%   04_altitude_hold         Fused altitude and independent altitude sensors
%   05_lidar_map_scans       Room map, accumulated scans and raw scan views
%   06_nis_gating            Innovation consistency for all measurement types
%   07_icp_diagnostics       ICP RMSE, overlap, corrections and acceptance
%   08_sensor_health         Availability, update counts and estimator health
%   09_bias_estimation       IMU and barometer bias convergence
%
% Inputs are the structs returned/generated by run_S2_lidar_slam.

fprintf('\n[PLOT] SINGLE-TABBED DASHBOARD v4 — %s\n', upper(label));
cleanupLegacyS2PlotWindows(label);
if ~exist(results_dir,'dir'), mkdir(results_dir); end
set(groot,'DefaultAxesFontSize',11, ...
          'DefaultLineLineWidth',1.25, ...
          'DefaultAxesBox','off', ...
          'DefaultFigureColor','w');

prefix = sprintf('S2_visual_slam_%s',lower(label));
cTruth = [0.10 0.10 0.10];
cEst   = [0.00 0.45 0.74];
cVio   = [0.85 0.33 0.10];
cLocal = [0.49 0.18 0.56];
cGlobal= [0.00 0.60 0.40];
cWarn  = [0.75 0.10 0.10];

% One MATLAB window for the whole Stage-S2 report. The outer tabs separate
% NOMINAL and STRESS trials; each trial contains nine report tabs.
[dashboardFig, trialTabs] = getTabbedDashboard(label);

% Derived quantities used by several figures.
imuOnly = computeImuOnlyBaseline(gt,imu,vio,cfg);
posAxisErr = est.p - gt.p;
vioTruth = gt.p(vio.idx,:);
vioPosErr = vecnorm(vio.p-vioTruth,2,2);
localErr = vecnorm(localLidar.pose(:,1:2)-lidarTruth(:,1:2),2,2);
globalErr = vecnorm(globalLidar(:,1:2)-lidarTruth(:,1:2),2,2);

estRpy = zeros(size(est.q,1),3);
for k=1:size(est.q,1), estRpy(k,:)=q2rpyPlot(est.q(k,:)); end
estRpy(:,3)=unwrap(estRpy(:,3));
rpyErr = estRpy-gt.rpy;
rpyErr(:,1)=wrapPiPlot(rpyErr(:,1));
rpyErr(:,2)=wrapPiPlot(rpyErr(:,2));
rpyErr(:,3)=wrapPiPlot(rpyErr(:,3));

%% 1. 6-DOF trajectory
[firstReportTab,tl]=newReportTab(trialTabs,'Trajectory',2,2, ...
    sprintf('Stage S2 6-DOF trajectory — %s',label));
tab=firstReportTab;

nexttile(tl);
plot3(gt.p(:,1),gt.p(:,2),gt.p(:,3),'--','Color',cTruth,'LineWidth',1.6); hold on;
plot3(est.p(:,1),est.p(:,2),est.p(:,3),'Color',cEst,'LineWidth',1.3);
scatter3(est.p(1,1),est.p(1,2),est.p(1,3),40,'filled','MarkerFaceColor',cGlobal);
scatter3(est.p(end,1),est.p(end,2),est.p(end,3),40,'filled','MarkerFaceColor',cWarn);
axis equal;grid on;view(-34,25);xlabel('x [m]');ylabel('y [m]');zlabel('z [m]');
legend('Ground truth','Local ESKF','Start','End','Location','best');title('3-D flight path');

nexttile(tl);
plot(gt.p(:,1),gt.p(:,2),'--','Color',cTruth,'LineWidth',1.6);hold on;
plot(est.p(:,1),est.p(:,2),'Color',cEst);drawRoom(cfg);axis equal;grid on;
xlabel('x [m]');ylabel('y [m]');title('Top view');

nexttile(tl);
plot(gt.p(:,1),gt.p(:,3),'--','Color',cTruth,'LineWidth',1.6);hold on;
plot(est.p(:,1),est.p(:,3),'Color',cEst);grid on;xlabel('x [m]');ylabel('z [m]');title('x-z projection');

nexttile(tl);
plot(gt.p(:,2),gt.p(:,3),'--','Color',cTruth,'LineWidth',1.6);hold on;
plot(est.p(:,2),est.p(:,3),'Color',cEst);grid on;xlabel('y [m]');ylabel('z [m]');title('y-z projection');
saveReportTab(tab,tl,results_dir,[prefix '_01_trajectory_6dof']);

%% 2. Position-error overlays
[tab,tl]=newReportTab(trialTabs,'Position errors',2,1, ...
    sprintf('Position-estimation errors — %s',label));

nexttile(tl);
semilogy(gt.t,max(1e-3,100*imuOnly.err),'Color',[0.55 0.55 0.55],'DisplayName','IMU only 3-D');hold on;
semilogy(gt.t,max(1e-3,100*est.posErr),'Color',cEst,'DisplayName','ESKF 3-D');
semilogy(vio.t(vio.valid),max(1e-3,100*vioPosErr(vio.valid)),'Color',cVio,'DisplayName','D435i VIO 3-D');
semilogy(lidar.t(localLidar.valid),max(1e-3,100*localErr(localLidar.valid)),'.','Color',cLocal,'MarkerSize',7,'DisplayName','LiDAR local XY');
semilogy(lidar.t(localLidar.valid),max(1e-3,100*globalErr(localLidar.valid)),'Color',cGlobal,'DisplayName','Global-map XY');
yline(100*cfg.requirement_m,'--','Color',cWarn,'Label','10 cm requirement','HandleVisibility','off');
grid on;xlim([0 cfg.duration]);ylabel('Error [cm, log]');legend('Location','best');
title(sprintf('Max ESKF after 5 s: %.2f cm | RMSE: %.2f cm', ...
    100*summary.fusedMaxAfter5_m,100*summary.fusedRMSEAfter5_m));

nexttile(tl);
plot(gt.t,100*posAxisErr(:,1),'DisplayName','x error');hold on;
plot(gt.t,100*posAxisErr(:,2),'DisplayName','y error');
plot(gt.t,100*posAxisErr(:,3),'DisplayName','z error');
yline( 100*cfg.requirement_m,'--','Color',cWarn,'HandleVisibility','off');
yline(-100*cfg.requirement_m,'--','Color',cWarn,'HandleVisibility','off');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Signed error [cm]');legend('Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_02_position_errors']);
copyPngAlias(results_dir,[prefix '_02_position_errors'],'S2_position_error.png');

%% 3. Attitude tracking
[tab,tl]=newReportTab(trialTabs,'Attitude',2,2, ...
    sprintf('Quaternion ESKF attitude tracking — %s',label));
attNames={'Roll','Pitch','Yaw'};
for j=1:3
    nexttile(tl);
    plot(gt.t,rad2deg(gt.rpy(:,j)),'--','Color',cTruth,'DisplayName','Truth');hold on;
    plot(gt.t,rad2deg(estRpy(:,j)),'Color',cEst,'DisplayName','ESKF');
    grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel([attNames{j} ' [deg]']);
    title(attNames{j});if j==1,legend('Location','best');end
end
nexttile(tl);
plot(gt.t,rad2deg(est.attErr),'Color',cEst);hold on;
yline(cfg.attRequirement_deg,'--','Color',cWarn,'Label','Attitude limit');
plot(gt.t,abs(rad2deg(rpyErr(:,1))),':','DisplayName','|roll error|');
plot(gt.t,abs(rad2deg(rpyErr(:,2))),':','DisplayName','|pitch error|');
plot(gt.t,abs(rad2deg(rpyErr(:,3))),':','DisplayName','|yaw error|');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Error [deg]');
title(sprintf('Maximum after 5 s: %.3f deg',summary.attMaxAfter5_deg));legend('Total quaternion error','Limit','Roll','Pitch','Yaw','Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_03_attitude_tracking']);

%% 4. Altitude hold and backup sensors
rangeZ=nan(size(alt.zr));
for i=1:numel(alt.tr)
    if ~alt.validR(i),continue;end
    k=alt.ir(i);R=q2RPlot(est.q(k,:));dW=R*cfg.d_BR;lever=R*cfg.r_BR;
    rangeZ(i)=-alt.zr(i)*dW(3)-lever(3);
end
baroBiasAtBaro=interp1(gt.t,est.bbaro,alt.tb,'linear','extrap');
baroCorrected=alt.zb-baroBiasAtBaro;

[tab,tl]=newReportTab(trialTabs,'Altitude',2,1, ...
    sprintf('Altitude hold and vertical-sensor redundancy — %s',label));
nexttile(tl);
plot(gt.t,100*gt.p(:,3),'--','Color',cTruth,'LineWidth',1.5,'DisplayName','Ground truth');hold on;
plot(gt.t,100*est.p(:,3),'Color',cEst,'DisplayName','ESKF altitude');
plot(vio.t(vio.valid),100*vio.p(vio.valid,3),'.','Color',cVio,'MarkerSize',3,'DisplayName','D435i VIO z');
yline(115,'k:','Nominal 1.15 m','HandleVisibility','off');
grid on;xlim([0 cfg.duration]);ylabel('Altitude [cm]');legend('Location','best');
title(sprintf('Maximum vertical error: %.2f cm',100*max(abs(posAxisErr(:,3)))));

nexttile(tl);
plot(alt.tr,100*rangeZ,'.','Color',cLocal,'MarkerSize',5,'DisplayName','Range-derived body z');hold on;
plot(alt.tb,100*baroCorrected,'Color',cGlobal,'DisplayName','Bias-corrected barometer');
plot(gt.t,100*gt.p(:,3),'--','Color',cTruth,'DisplayName','Ground truth');
invalid=~alt.validR;plot(alt.tr(invalid),100*gt.p(alt.ir(invalid),3),'x','Color',cWarn,'DisplayName','Range unavailable');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Equivalent altitude [cm]');legend('Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_04_altitude_hold']);
copyPngAlias(results_dir,[prefix '_04_altitude_hold'],'S2_altitude_hold.png');

%% 5. LiDAR room map and representative scans
[tab,tl]=newReportTab(trialTabs,'LiDAR map',1,2, ...
    sprintf('RPLidar local mapping and ScanContext global consistency — %s',label));

nexttile(tl);hold on;
validIdx=find(localLidar.valid);
if ~isempty(validIdx)
    stride=max(1,floor(numel(validIdx)/30));
    mapPts=[];
    for n=1:stride:numel(validIdx)
        i=validIdx(n);mapPts=[mapPts;transform2D(lidar.scans{i}(1:3:end,:),globalLidar(i,:))]; %#ok<AGROW>
    end
    if ~isempty(mapPts),scatter(mapPts(:,1),mapPts(:,2),2,[0.65 0.65 0.65],'filled','DisplayName','Accumulated scans');end
end
plot(lidarTruth(:,1),lidarTruth(:,2),'--','Color',cTruth,'LineWidth',1.4,'DisplayName','LiDAR truth');
plot(localLidar.pose(:,1),localLidar.pose(:,2),'Color',cLocal,'DisplayName','Local ICP');
plot(globalLidar(:,1),globalLidar(:,2),'Color',cGlobal,'DisplayName','Global pose graph');
if ~isempty(keyframes),scatter(globalLidar(keyframes,1),globalLidar(keyframes,2),10,cEst,'filled','DisplayName','Keyframes');end
for n=1:size(loops,1)
    i=loops(n,1);j=loops(n,2);
    plot(globalLidar([i j],1),globalLidar([i j],2),'-','Color',[0.90 0.55 0.10],'LineWidth',1.0,'HandleVisibility','off');
end
drawRoom(cfg);axis equal;grid on;xlabel('x [m]');ylabel('y [m]');
title(sprintf('Loops: %d | return error local/global: %.1f / %.1f cm', ...
    summary.verifiedLoops,100*summary.localReturnError_m,100*summary.globalReturnError_m));
legend('Location','bestoutside');

nexttile(tl);hold on;
scanIds=unique(round(linspace(1,numel(lidar.scans),3)));
scanColors=[0.00 0.45 0.74;0.85 0.33 0.10;0.49 0.18 0.56];
for n=1:numel(scanIds)
    s=lidar.scans{scanIds(n)};
    plot(s(:,1),s(:,2),'.','Color',scanColors(n,:),'MarkerSize',4, ...
        'DisplayName',sprintf('t = %.1f s',lidar.t(scanIds(n))));
end
axis equal;grid on;xlabel('LiDAR x [m]');ylabel('LiDAR y [m]');
title('Representative raw scans in sensor frame');legend('Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_05_lidar_map_scans']);
copyPngAlias(results_dir,[prefix '_05_lidar_map_scans'],'S2_slam_map.png');

%% 6. NIS consistency and gating
[tab,tl]=newReportTab(trialTabs,'NIS gating',2,2, ...
    sprintf('Normalized innovation squared and outlier gates — %s',label));
plotNIS(nexttile(tl),est.nis.vio_t,est.nis.vio,cfg.gateVIO9,'D435i VIO (9 DOF)',summary.counts.vioRej,cWarn);
plotNIS(nexttile(tl),est.nis.lidar_t,est.nis.lidar,cfg.gateLidar3,'LiDAR x-y-yaw (3 DOF)',summary.counts.lidarRej,cWarn);
plotNIS(nexttile(tl),est.nis.range_t,est.nis.range,cfg.gate1,'Downward range (1 DOF)',summary.counts.rangeRej,cWarn);
plotNIS(nexttile(tl),est.nis.baro_t,est.nis.baro,cfg.gate1,'Barometer (1 DOF)',summary.counts.baroRej,cWarn);
saveReportTab(tab,tl,results_dir,[prefix '_06_nis_gating']);

%% 7. ICP diagnostics
[tab,tl]=newReportTab(trialTabs,'ICP diagnostics',2,2, ...
    sprintf('LiDAR scan-to-map ICP diagnostics — %s',label));

nexttile(tl);
plot(lidar.t,100*localLidar.diag(:,1),'Color',cLocal);hold on;
yline(100*cfg.icpHealthRMSE,'--','Color',cWarn,'Label','RMSE gate');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('ICP RMSE [cm]');

nexttile(tl);
plot(lidar.t,localLidar.diag(:,2),'Color',cEst);hold on;
yline(cfg.icpHealthOverlap,'--','Color',cWarn,'Label','Minimum overlap');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Matched points');

nexttile(tl);
plot(lidar.t,100*localLidar.diag(:,6),'Color',cGlobal,'DisplayName','XY correction');hold on;
yline(100*cfg.icpHealthCorrection,'--','Color',cWarn,'Label','XY gate','HandleVisibility','off');
plot(lidar.t,rad2deg(localLidar.diag(:,7)),'Color',cVio,'DisplayName','Yaw correction [deg]');
yline(rad2deg(cfg.icpHealthYaw),':','Color',cWarn,'Label','Yaw gate','HandleVisibility','off');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Correction [cm / deg]');legend('Location','best');

nexttile(tl);
stairs(lidar.t,double(localLidar.diag(:,3)),'Color',[0.40 0.40 0.40],'DisplayName','Geometric health');hold on;
stairs(lidar.t,double(localLidar.valid),'Color',cGlobal,'DisplayName','Accepted by ESKF');
ylim([-0.1 1.2]);grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Boolean');legend('Location','best');
title(sprintf('Healthy fraction: %.1f%%',100*summary.lidarHealthyFraction));
saveReportTab(tab,tl,results_dir,[prefix '_07_icp_diagnostics']);

%% 8. Sensor and estimator health
[tab,tl]=newReportTab(trialTabs,'Sensor health',2,1, ...
    sprintf('Sensor availability and estimator health — %s',label));
nexttile(tl);hold on;
stairs(gt.t,0.10+0.70*double(est.health),'Color',cEst,'DisplayName','Estimator healthy');
stairs(alt.tr,1.10+0.70*double(alt.validR),'Color',cGlobal,'DisplayName','Range available');
stairs(lidar.t,2.10+0.70*double(localLidar.valid),'Color',cLocal,'DisplayName','LiDAR accepted');
stairs(vio.t,3.10+0.70*double(vio.valid),'Color',cVio,'DisplayName','D435i VIO available');
yticks([0.45 1.45 2.45 3.45]);yticklabels({'ESKF','Range','LiDAR','VIO'});ylim([0 4.0]);
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');title(sprintf('Unhealthy ESKF samples: %d',summary.unhealthySamples));legend('Location','best');

nexttile(tl);
accepted=[summary.counts.vioAcc summary.counts.lidarAcc summary.counts.rangeAcc summary.counts.baroAcc];
rejected=[summary.counts.vioRej summary.counts.lidarRej summary.counts.rangeRej summary.counts.baroRej];
b=bar(categorical({'VIO','LiDAR','Range','Barometer'}),[accepted(:),rejected(:)],'stacked');
b(1).DisplayName='Accepted';b(2).DisplayName='Rejected';ylabel('Updates');grid on;legend('Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_08_sensor_health']);

%% 9. Bias estimation
[tab,tl]=newReportTab(trialTabs,'Bias estimation',3,1, ...
    sprintf('Estimated sensor biases — %s',label));
axesNames={'x','y','z'};
nexttile(tl);hold on;
for j=1:3
    plot(gt.t,imu.baTrue(:,j),'--','DisplayName',['True b_a ' axesNames{j}]);
    plot(gt.t,est.ba(:,j),'DisplayName',['Estimated b_a ' axesNames{j}]);
end
grid on;xlim([0 cfg.duration]);ylabel('Accel bias [m/s^2]');legend('Location','eastoutside');

nexttile(tl);hold on;
for j=1:3
    plot(gt.t,rad2deg(imu.bgTrue(:,j)),'--','DisplayName',['True b_g ' axesNames{j}]);
    plot(gt.t,rad2deg(est.bg(:,j)),'DisplayName',['Estimated b_g ' axesNames{j}]);
end
grid on;xlim([0 cfg.duration]);ylabel('Gyro bias [deg/s]');legend('Location','eastoutside');

nexttile(tl);
plot(alt.tb,100*alt.baroBiasTrue,'--','Color',cTruth,'DisplayName','True barometer bias');hold on;
plot(gt.t,100*est.bbaro,'Color',cGlobal,'DisplayName','Estimated barometer bias');
grid on;xlim([0 cfg.duration]);xlabel('Time [s]');ylabel('Bias [cm]');legend('Location','best');
saveReportTab(tab,tl,results_dir,[prefix '_09_bias_estimation']);

% Return this trial to its first report tab.
trialTabs.SelectedTab = firstReportTab;
drawnow;

% Save the complete editable dashboard once. After the STRESS call this FIG
% contains NOMINAL and STRESS outer tabs and all report tabs.
dashboardPath = fullfile(fileparts(results_dir),'S2_visual_slam_dashboard.fig');
savefig(dashboardFig,dashboardPath);

fprintf('\n9 report tabs exported to:\n  %s\n',results_dir);
fprintf('Tabbed dashboard saved to:\n  %s\n',dashboardPath);
end

% -------------------------------------------------------------------------
function plotNIS(ax,t,n,gate,plotTitle,rejected,cWarn)
axes(ax); %#ok<LAXES>
if isempty(n)
    text(0.5,0.5,'No attempted measurements','HorizontalAlignment','center');
    axis off;title(plotTitle);return;
end
semilogy(t,max(n,1e-6),'.-','MarkerSize',5);hold on;
yline(gate,'--','Color',cWarn,'Label','99.9% gate');
grid on;xlabel('Time [s]');ylabel('NIS [log]');title(sprintf('%s | rejected: %d',plotTitle,rejected));
end

function drawRoom(cfg)
rectangle('Position',[0 0 cfg.room(1) cfg.room(2)],'EdgeColor',[0.15 0.15 0.15],'LineWidth',1.5,'HandleVisibility','off');
for i=1:size(cfg.obstacles,1)
    rectangle('Position',cfg.obstacles(i,:),'FaceColor',[0.80 0.80 0.80], ...
        'EdgeColor',[0.30 0.30 0.30],'HandleVisibility','off');
end
if isfield(cfg,'geofence')
    g=cfg.geofence;
    geofenceColor=[0.05 0.60 0.20];

    % Rectangle objects do not support DisplayName in all MATLAB releases.
    % Keep the rectangle itself out of the legend and add an invisible
    % NaN line as a release-compatible legend proxy.
    rectangle('Position',[g(1) g(3) g(2)-g(1) g(4)-g(3)], ...
        'EdgeColor',geofenceColor,'LineStyle','--','LineWidth',1.4, ...
        'HandleVisibility','off');
    plot(nan,nan,'--','Color',geofenceColor,'LineWidth',1.4, ...
        'DisplayName','Safe geofence');
end
if isfield(cfg,'geofenceMarginXY')
    for i=1:size(cfg.obstacles,1)
        o=cfg.obstacles(i,:);m=cfg.geofenceMarginXY;
        x0=max(0,o(1)-m);y0=max(0,o(2)-m);
        x1=min(cfg.room(1),o(1)+o(3)+m);y1=min(cfg.room(2),o(2)+o(4)+m);
        rectangle('Position',[x0 y0 x1-x0 y1-y0], ...
            'EdgeColor',[0.85 0.10 0.05],'LineStyle',':','LineWidth',1.2, ...
            'HandleVisibility','off');
    end
end
xlim([0 cfg.room(1)]);ylim([0 cfg.room(2)]);
end

function cleanupLegacyS2PlotWindows(label)
% Remove stale Stage-S2 report windows left by older plotting functions.
% The live animation is deliberately preserved because it has its own tag.
if ~strcmpi(label,'NOMINAL'), return; end
figs=findall(groot,'Type','figure');
for k=1:numel(figs)
    f=figs(k);
    try, nm=string(f.Name); catch, nm=""; end
    try, tg=string(f.Tag);  catch, tg=""; end
    isAnimation=contains(lower(nm),'flight animation') || contains(lower(tg),'animation');
    isStage2=contains(lower(nm),'stage s2') || contains(lower(nm),'s2 ') || ...
             contains(lower(tg),'s2visualslam') || contains(lower(tg),'s2report');
    if isStage2 && ~isAnimation
        delete(f);
    end
end
end

function [dashboardFig,trialTabs]=getTabbedDashboard(label)
% GETTABBEDDASHBOARD creates one reusable report window. A new NOMINAL run
% resets stale dashboards; the following STRESS run is appended to it.
tag='S2VisualSLAMSingleDashboardV4';
if strcmpi(label,'NOMINAL')
    old=findall(groot,'Type','figure','Tag',tag);
    if ~isempty(old),delete(old);end
end

dashboardFig=findall(groot,'Type','figure','Tag',tag);
if isempty(dashboardFig) || ~isvalid(dashboardFig(1))
    dashboardFig=figure('Name','Stage S2 — 6-DOF navigation dashboard', ...
        'NumberTitle','off','Tag',tag,'Color','w', ...
        'Position',[35 55 1500 900]);
    outer=uitabgroup(dashboardFig,'Units','normalized', ...
        'Position',[0 0 1 1],'Tag','S2OuterTrialTabs');
else
    dashboardFig=dashboardFig(1);
    figure(dashboardFig);
    outer=findobj(dashboardFig,'Type','uitabgroup','Tag','S2OuterTrialTabs');
    if isempty(outer)
        outer=uitabgroup(dashboardFig,'Units','normalized', ...
            'Position',[0 0 1 1],'Tag','S2OuterTrialTabs');
    else
        outer=outer(1);
    end
end

trialTag=['S2Trial_' lower(label)];
oldTrial=findobj(outer,'Type','uitab','Tag',trialTag);
if ~isempty(oldTrial),delete(oldTrial);end
trialTab=uitab(outer,'Title',upper(label),'Tag',trialTag);
trialTabs=uitabgroup(trialTab,'Units','normalized', ...
    'Position',[0 0 1 1],'Tag',['S2Reports_' lower(label)]);
outer.SelectedTab=trialTab;
end

function [tab,tl]=newReportTab(trialTabs,tabTitle,nRows,nCols,overallTitle)
tab=uitab(trialTabs,'Title',tabTitle);
tl=tiledlayout(tab,nRows,nCols,'TileSpacing','compact','Padding','compact');
title(tl,overallTitle,'FontWeight','normal');
end

function saveReportTab(tab,tl,results_dir,baseName)
% Export only the current tab's tiled layout, without creating a new window.
pngPath=fullfile(results_dir,[baseName '.png']);
tab.Parent.SelectedTab=tab;
drawnow;
exportgraphics(tl,pngPath,'Resolution',220);
end


function copyPngAlias(results_dir,baseName,aliasName)
source=fullfile(results_dir,[baseName '.png']);
target=fullfile(results_dir,aliasName);
if exist(source,'file')==2,copyfile(source,target,'f');end
end

function out=computeImuOnlyBaseline(gt,imu,vio,cfg)
% Open-loop strapdown baseline using the same first VIO initialization but
% no VIO, LiDAR, range, barometer or bias corrections thereafter.
N=numel(gt.t);dt=1/cfg.imuRate;p=zeros(N,3);v=zeros(N,3);q=zeros(N,4);
p(1,:)=vio.p(1,:);v(1,:)=vio.v(1,:);q(1,:)=qNormalizePlot(vio.q(1,:));
for k=2:N
    R=q2RPlot(q(k-1,:));aw=R*imu.acc(k,:).'+cfg.gW;
    p(k,:)=p(k-1,:)+v(k-1,:)*dt+0.5*aw.'*dt^2;
    v(k,:)=v(k-1,:)+aw.'*dt;
    q(k,:)=qMultiplyPlot(q(k-1,:),qExpPlot(imu.gyro(k,:)*dt));
end
out.p=p;out.err=vecnorm(p-gt.p,2,2);
end

function q=qNormalizePlot(q)
q=q(:).';q=q/norm(q);if q(1)<0,q=-q;end
end

function q=qMultiplyPlot(a,b)
a=a(:).';b=b(:).';
q=[a(1)*b(1)-dot(a(2:4),b(2:4)), ...
   a(1)*b(2:4)+b(1)*a(2:4)+cross(a(2:4),b(2:4))];
q=qNormalizePlot(q);
end

function q=qExpPlot(v)
v=v(:).';a=norm(v);
if a<1e-10,q=qNormalizePlot([1 0.5*v]);else,q=[cos(a/2) sin(a/2)*v/a];end
end

function P=transform2D(P,pose)
c=cos(pose(3));s=sin(pose(3));R=[c -s;s c];
P=P*R.'+pose(1:2);
end

function rpy=q2rpyPlot(q)
R=q2RPlot(q);pitch=asin(max(-1,min(1,-R(3,1))));
roll=atan2(R(3,2),R(3,3));yaw=atan2(R(2,1),R(1,1));
rpy=[roll pitch yaw];
end

function R=q2RPlot(q)
q=q(:).';q=q/norm(q);w=q(1);x=q(2);y=q(3);z=q(4);
R=[1-2*(y^2+z^2),2*(x*y-z*w),2*(x*z+y*w); ...
   2*(x*y+z*w),1-2*(x^2+z^2),2*(y*z-x*w); ...
   2*(x*z-y*w),2*(y*z+x*w),1-2*(x^2+y^2)];
end

function a=wrapPiPlot(a)
a=mod(a+pi,2*pi)-pi;
end
