function gate = validate_S2_4_AD(trialMat,outputDir)
% VALIDATE_S2_4_AD Execute the cumulative MATLAB A-D shadow gate twice.
% Exact repeat comparison is required before the shadow package may pass.
arguments
    trialMat (1,:) char
    outputDir (1,:) char = ''
end
if isempty(outputDir)
    outputDir=fullfile(fileparts(trialMat),'S2_4_AD_shadow_validation');
end
if exist(outputDir,'dir')~=7,mkdir(outputDir);end
r1=run_S2_4_AD_shadow_replay(trialMat,fullfile(outputDir,'repeat_1'));
r2=run_S2_4_AD_shadow_replay(trialMat,fullfile(outputDir,'repeat_2'));
uncertaintyExact=strcmp(r1.uncertaintyDeterministicDigest,r2.uncertaintyDeterministicDigest);
frontierViewpointExact=strcmp(r1.frontierViewpointDigest,r2.frontierViewpointDigest);
countsExact=r1.snapshotCount==r2.snapshotCount && ...
    r1.frontierTrackCount==r2.frontierTrackCount && ...
    r1.acceptedCandidateCount==r2.acceptedCandidateCount && ...
    r1.unsafeAcceptedCandidates==r2.unsafeAcceptedCandidates;
gate=struct( ...
    'parentExactMapperReplay',r1.parentExactMapperReplay&&r2.parentExactMapperReplay, ...
    'mapperArraysExact',r1.mapperArraysExact&&r2.mapperArraysExact, ...
    'uncertaintyReplayDeterministic',uncertaintyExact, ...
    'frontierViewpointReplayDeterministic',frontierViewpointExact, ...
    'repeatCountsExact',countsExact, ...
    'frontierReplayCompleted',r1.snapshotCount>0, ...
    'acceptedCandidateCount',r1.acceptedCandidateCount, ...
    'unsafeAcceptedCandidates',r1.unsafeAcceptedCandidates, ...
    'truthIsolation',r1.truthAccessCount==0&&r2.truthAccessCount==0, ...
    'commandIsolation',~r1.commandIssued&&~r2.commandIssued, ...
    'pass',false);
gate.pass=r1.pass&&r2.pass&&uncertaintyExact&&frontierViewpointExact&&countsExact;
save(fullfile(outputDir,'S2_4_AD_validation_gate.mat'),'gate','r1','r2');
if ~gate.pass,error('S2_4:ADGate','S2.4 A-D shadow validation failed.');end
end
