function state = init_quadrotor_state_S2_2(cfg,startXY)
state=struct('p',[startXY(:);cfg.altitudeNominal_m],'v',zeros(3,1), ...
    'q',[1 0 0 0],'omega',zeros(3,1),'a',zeros(3,1),'omegaDot',zeros(3,1), ...
    'thrust_N',cfg.mass_kg*norm(cfg.gW),'moment_Nm',zeros(3,1));
end
