function p = project_uncertainty_2d_S2_4(u,map,altitude)
% PROJECT_UNCERTAINTY_2D_S2_4 Project sidecar layers at nominal altitude.
arguments
    u (1,1) struct
    map (1,1) struct
    altitude (1,1) double
end
[~,iz] = min(abs(double(map.zs)-altitude));
p = struct( ...
    'entropy',u.entropy(:,:,iz), ...
    'observationCount',u.observationCount(:,:,iz), ...
    'lastObservedTime',u.lastObservedTime(:,:,iz), ...
    'observationAge',u.observationAge(:,:,iz), ...
    'sourceMask',u.sourceMask(:,:,iz), ...
    'sourceQuality',u.sourceQuality(:,:,iz), ...
    'staticConfidence',u.staticConfidence(:,:,iz), ...
    'dynamicConfidence',u.dynamicConfidence(:,:,iz), ...
    'staleFree',u.staleFree, ...
    'lastObservedXY',max(double(map.lastObserved),[],3));
end
